highlighter: pygments
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
source: .
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "base"